---
- name: Create key directory
  file:
    dest: "{{ openvpn_local_key_path }}"
    state: directory
  delegate_to: localhost
  run_once: true

- name: Gen CA key
  openssl_privatekey:
    path: "{{ openvpn_local_key_path }}/{{ openvpn_ca_key }}"
    size: "{{ openvpn_key_size }}"
  delegate_to: localhost
  run_once: true
  notify: restart openvpn

- name: Create request
  openssl_csr:
    path: "{{ openvpn_local_key_path }}/{{ openvpn_ca_csr }}"
    privatekey_path: "{{ openvpn_local_key_path }}/{{ openvpn_ca_key }}"
    common_name: "{{ openvpn_ca_cn }}"
    basic_constraints:
      - "CA:TRUE"
  delegate_to: localhost
  run_once: true

- name: Generate a Self Signed OpenSSL certificate
  openssl_certificate:
    path: "{{ openvpn_local_key_path }}/{{ openvpn_ca_crt }}"
    privatekey_path: "{{ openvpn_local_key_path }}/{{ openvpn_ca_key }}"
    csr_path: "{{ openvpn_local_key_path }}/{{ openvpn_ca_csr }}"
    provider: selfsigned
  delegate_to: localhost
  run_once: true
  notify: restart openvpn
