---
- name: Creates directory
  become: true
  file:
    path: "{{ openvpn_config_path }}"
    state: directory

- name: Gen server key
  become: true
  openssl_privatekey:
    path: "{{ openvpn_config_path }}/{{ openvpn_host_key }}"
    size: "{{ openvpn_key_size }}"
  notify: restart openvpn

- name: Create request
  become: true
  become_method: sudo
  openssl_csr:
    path: "{{ openvpn_config_path }}/{{ openvpn_host_csr }}"
    privatekey_path: "{{ openvpn_config_path }}/{{ openvpn_host_key }}"
    common_name: "{{ openvpn_host_cn }}"

- name: Get request synchronize
  become: true
  become_method: sudo
  synchronize:
    src: "{{ openvpn_config_path }}/{{ openvpn_host_csr }}"
    dest: "{{ openvpn_local_key_path }}/{{ openvpn_host_csr }}"
    #flat: true
  when: openvpn_role == 'server'

- name: Create key directory
  local_action:
    module: file
    dest: "{{ openvpn_local_key_path }}"
    state: directory
    mode: '0666'
  when: openvpn_role == 'client'

- name: Get request fetch
  become: true
  become_method: sudo
  shell: "{{ item }}"
  with_items:
    - cp "{{ openvpn_config_path }}/{{ openvpn_host_csr }}" "{{home_path}}/{{ openvpn_local_key_path }}/{{ openvpn_host_csr }}"
    - chmod 666 "{{ openvpn_config_path }}/{{ openvpn_host_csr }}" "{{ openvpn_local_key_path }}/{{ openvpn_host_csr }}"
  when: openvpn_role == 'client'

- name: Generate an OpenSSL certificate signed with your own CA certificate
  become: true
  local_action:
    module: openssl_certificate
    path: "{{ openvpn_local_key_path }}/{{ openvpn_host_crt }}"
    csr_path: "{{ openvpn_local_key_path }}/{{ openvpn_host_csr }}"
    ownca_path: "{{ openvpn_local_key_path }}/{{ openvpn_ca_crt }}"
    ownca_privatekey_path: "{{ openvpn_local_key_path }}/{{ openvpn_ca_key }}"
    provider: ownca

# - name: Copy certificate
#   become: true
#   shell: "{{ item }}"
#   with_items:
#     - cp "{{ openvpn_local_key_path }}/{{ openvpn_host_crt }}" "{{ openvpn_config_path }}/{{ openvpn_host_crt }}"
#   notify: restart openvpn

  - name: Copy certificate
  become: true
  copy:
    src: "{{ openvpn_local_key_path }}/{{ openvpn_host_crt }}"
    dest: "{{ openvpn_config_path }}/{{ openvpn_host_crt }}"
  notify: restart openvpn
